### ISSUE TITLE
How to play file with the internal media player (Solved)

### ISSUE THREAD

**Issue by danrobi11** [pinnaculum/galacteek#12] opened 2020-04-30 19:29 UTC
I've open the media player and seems like its asking for playlist
You told me to load a video from #video and its working. I see the 'save playlist' option. 
So we need to add a file in #video to load in media player and how do we do add a file as #video?
I think it would be useful to implement same sort of 'browse system file side panel' like in the file manager tab in order to easily load a file in the media player. Maybe thats not intended, idk.

**Comment by danrobi11** [comment] 2020-04-30 20:28
Ok got it
From the file manger tab open the video section. Drag/drop from the file and add to hashmark. From there we can add tag etc, neat!

**Comment by pinnaculum** [comment] 2020-04-30 21:25
You don't need to use #video or any tags to read videos, it's just that i used this tag for a few videos and it was a quick way to find them.

Once you've imported a multimedia file in IPFS from the filemanager, double-clicking the video or music file should automatically open the file with the mediaplayer, queuing it in the playlist. Also you can do Right click on the file and then select *Open*.

You can also load medias in the mediaplayer by using the clipboard. If the clipboard contains an IPFS address to a multimedia file, click on the button with a clipboard icon at the bottom left and it will be loaded in the playlist. 

Thanks for testing!

**Comment by danrobi11** [comment] 2020-05-01 05:58
Ok I got big request. Let the clipboard clip to host. Fighting to clip to host getting the best out of me now. I've tried very hard to find a way to clip the CID of my video to the host clipboard.
We need to be able to share the CID outside of Galacteek.
Allowing clipping to the host clipboard would fix this headache, no?
Im able to clip the CID to host only websites from the URL bar with ctrl+c. However, I cant do that with a video theres no URL bar in the media player.

**Comment by danrobi11** [comment] 2020-05-01 06:47
I did same as I do with websites and I get this result:
```
ipfs resolve -r /ipns/bafzbeia5upr4rtfv7jm7vo677dheaotyj72mzoe36lq7bctcvpfojzcxai/How%20To%20MuWire%20Chat%20Functionality%20Demo.m4v: routing: not found
```
Is this because its a video or because I've added the video to my DID?

**Comment by pinnaculum** [comment] 2020-05-01 10:26
I've made a change so that it will copy to all clipboards (primary and system clipboard) so that you can use ctrl+v from outside. Also you'll be able to copy a pyramid's address accessible with ipfs.io gateway (https://ipfs.io/ipns/...) to the clipboard.

For the resolving: i don't have this issue, i'm able to resolve IPNS keys of pyramids with 'ipfs resolve ..'. Where are you running the 'ipfs resolve' from (local ?) and what does 'ipfs id' say ? Check that you're using the right daemon with IPFS_PATH. If you want to run commands with 'ipfs' using galacteek's ipfs daemon, do:

> export IPFS_PATH=$HOME/.local/share/galacteek/<profile>/ipfs

<profile> will be the profile name (*main* is the default).

The issue i have right now with go-ipfs 0.5.0 is IPNS publishing (i get *context deadline exceeded* errors when publishing). Do you see 'Publish failed' errors in the galacteek logs ?

**Comment by danrobi11** [comment] 2020-05-01 16:15
Yes same here. Whatever I put into my pyramide return as publish failed.
I dont understand the thing you're asking above. Let me know when the 'publish failed' is fixed on your end, nothing work here for me, always same publish failed

**Comment by danrobi11** [comment] 2020-05-01 16:21
Its working when I add the file to ipfs-desktop only.
https://ipfs.io/ipfs/QmSLhms7Cs8QkUkPMtsWH1j5vFCwNgFpvu2n6cJiSN8F4H?filename=How%20To%20MuWire%20Chat%20Functionality%20Demo.m4v

**Comment by pinnaculum** [comment] 2020-05-01 22:21
Nothing to do with galacteek this is an issue with timeouts in IPNS publishing with go-ipfs 0.5.0, see [this issue](https://github.com/ipfs/go-ipfs/issues/7244) for more details.

**Comment by danrobi11** [comment] 2020-05-02 19:55
Ok pyramide working now with new appimage ff707ef9-x86_64
Thx for the pyramide fix, clipboard to host, new editor tab, edit pyramide content. Thats what I've noticed so far. Nice work thank you :)

**Comment by danrobi11** [comment] 2020-05-02 20:16
No. I restarted galacteek and I now have the pyramids publish failed again.
It did work tho, I've watched the content from a regular browser.

**Comment by pinnaculum** [comment] 2020-05-02 20:25
Yes i've made a new image. It uses the latest version of go-ipfs (compiled from master).

It's normal if the publish fails sometimes. No matter what galacteek should retry again to publish if the previous attempt failed.

What has changed most is the editor, you can edit a whole directory object and not just single files. Right-click on the left-side filesystem view to add files and directories. Once you save, a copy goes in the history. Click on the clipboard icon in the history to load it in the clipboard manager, and then from the pyramid you can publish this clipboard item. Please report any bugs, problems, ideas about the editor.

Also there are two atom feeds produced, one with pure IPFS URLs and one with URLs that use a public ipfs gateway, to be used with any feed reader (tested with rssguard), the filename is *dfeed.publicgw.atom*

**Comment by danrobi11** [comment] 2020-05-02 21:00
Very nice! working here with thunderbird. I now have new address because seems like I have new ID or something. My blog and feed was gone, idk why. Heres my new public blog feed:
https://ipfs.io/ipns/bafzbeicv64lbgygcfht6ldmn6y2qltupnzwr6r4tbgyxc6ozxkc73ibxhy/dfeed.publicgw.atom

When we copy we're copying only /ipns/bafzbe... not https://ipfs.io/ipns/bafzbe...
Mostly every new users will get stuck copying /ipns/bafzbe...
Same when we copy pyramide IPNS address. 
I bet theres a good reason why we're copying only /ipns/bafzbe... I also bet only /ipns/bafzbe... will create a lot of issues with new users. 

I thought of something. In pyramide another option to copy the https://ipfs.io/ipns/bafzbe... 
And since the regular feed address icon is designed to be used with regular feed reader client, galacteek should copy https://ipfs.io/ipns/bafzbe...

**Comment by pinnaculum** [comment] 2020-05-02 22:03
I can access your blog, very nice ! Hashmarked ! Did you use a new profile ? That could be the explanation.

The browser recognizes these two different URLs as different representations of the same IPFS object (IPFS raw path, and with gateway). I will make a change so that from a webpage, and in other menus, you can copy to the clipboard the URL of the object accessible from a public IPFS gateway (ipfs.io or others). I'll create an issue for that.

Thanks a lot.

**Comment by danrobi11** [comment] 2020-05-03 00:03
Seems like when I run Galacteek as standalone I've not the same profile or the saved blog/feed are not saved at the same place, because:
Since I've created the new blog and feed with the ipfs-desktop daemon my blog and feed shows up only when im running with the ipfs-desktop daemon. Empty blog and feed if I run with the galacteek daemon

**Comment by pinnaculum** [comment] 2020-05-03 11:57
Yes of course, because in each case you're running a different daemon which has its own repository. Galacteek stores information in the MFS (Mutable File System) of the repository

**Comment by danrobi11** [comment] 2020-05-04 19:01
The media player keeps blinking when im watching these videos:
- /ipns/QmfEVLwuuZHCdy28PFLptuQ1pR4PCvW6atCVZNmZn5C2si
- /ipns/QmfZZ8xp9Y74LxQ1RAn6BbLnewWXBGZiKPdZspEWkNSdjq
- /ipns/QmZs8hLu1RtWXtEuE1ob8xnW86aBKtrtz3iytG8DcmSjEN
I've found a workaround for the blinking player issue.
Im showing the blinking player workaround in this demo video: /ipns/QmWVtxeEuQiUoPcJZt2zpeALge58JfsjBjebRbw2AeztFL

My new blog address: ipns://bafzbeiap4j5yr6nhf3kjwdfqydxga4ld3jehdxw56rhrvfkfvmmzoogdm4/blog/index.html

**Comment by pinnaculum** [comment] 2020-05-04 19:59
@danrobi11 I remember having this issue randomly, i can definitely reproduce it, i'll create an issue this will be fixed in the next few days. I've watched your clip, very well done. Blinking doesn't occur in fullscreen mode for me.

If you have suggestions to improve the media player don't hesitate.

Thanks a lot !

**Comment by pinnaculum** [comment] 2020-05-04 20:25
The widget blinking issue has been fixed. Also double-clicks on the video widget will now switch to fullscreen.

**Comment by danrobi11** [comment] 2020-05-07 06:42
Regarding suggestions. I've found this and it got me thinking. What do you think about a URL search bar in the media player where the users could paste CID's and play instantly the video? 
https://github.com/astavares/bashflix

**Comment by danrobi11** [comment] 2020-05-11 02:36
Im in file manager, I copy the CID to clipboard. Works in my media player. However, If I send the CID to nicky, it doesnt work in nicky media player: bafybeihq7w25x67ajg5phdnednjpwaapf4rwz3e6e7ioxvwa7hnmepmipe

**Closed** 2020-07-03 12:05 UTC
